# Generated by Django 5.0 on 2023-12-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_Raven', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
    ]
