# Generated by Django 5.0 on 2023-12-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_Raven', '0002_remove_cliente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cliente',
        ),
    ]
