# Generated by Django 5.0 on 2023-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_Raven', '0003_remove_producto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('legajo', models.CharField(max_length=100)),
            ],
        ),
    ]
